name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start &
      
      - name: Wait for app to load
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run
